version: '3.7'

services: 
  # watch for pedestrians, turn on lights
  barad-dur:
    build: ./barad-dur
    restart: always
    devices:
      - "/dev/vcsm"
      - "/dev/vchiq"
    environment:
      - LATITUDE
      - LONGITUDE
      - ELEVATION
    volumes:
      - "~/.python_hue:/root/.python_hue"
    networks:
      - isengard

networks:
  isengard:
    external: True
