version: '3.7'

# adapted from https://github.com/influxdata/TICK-docker/blob/master/1.3/docker-compose.yml
services:

  # Define a Telegraf service
  #telegraf:
  #  image: telegraf:1.4.0
  #  volumes:
  #    - ./etc/telegraf.conf:/etc/telegraf/telegraf.conf:ro
  #  links:
  #    - influxdb
  #  ports:
  #    - "8092:8092/udp"
  #    - "8094:8094"
  #    - "8125:8125/udp"

  # Define an InfluxDB service
  influxdb:
    image: influxdb:1.7
    labels:
      - "traefik.http.routers.influxdb.rule=PathPrefix(`/influxdb/`)"
      - "traefik.http.middlewares.influxdb.stripprefix.prefixes=/influxdb"
      - "traefik.http.middlewares.influxdb.stripprefix.forceslash=true"
      - "traefik.http.routers.influxdb.middlewares=influxdb@docker"
    volumes:
      - ./data/influxdb:/var/lib/influxdb
    networks:
      - isengard-overlay

  # Define a Chronograf service
  chronograf:
    image: chronograf:1.8.0
    environment:
      INFLUXDB_URL: http://influxdb:8086
      KAPACITOR_URL: http://kapacitor:9092
      BASE_PATH: /chronograf
    labels:
      - "traefik.http.routers.chronograf.rule=PathPrefix(`/chronograf/`)"
    links:
      - influxdb
      - kapacitor
    networks:
      - isengard-overlay

  # Define a Kapacitor service
  kapacitor:
    image: kapacitor:1.3.3
    environment:
      - KAPACITOR_HOSTNAME=kapacitor
      - KAPACITOR_INFLUXDB_0_URLS_0=http://influxdb:8086
    links:
      - influxdb
      - sms-notifier
    ports:
      - "9092:9092"
    networks:
      - isengard-overlay
    volumes:
      - ./tickscripts:/usr/local/tickscripts
      - ./data/alerts:/var/log/alerts

  # Define a service for using the influx CLI tool.
  # docker-compose run influxdb-cli
  influxdb-cli:
    image: influxdb:1.3.5
    entrypoint:
      - influx
      - -host
      - influxdb
    links:
      - influxdb
    networks:
      - isengard-overlay

  # Define a service for using the kapacitor CLI tool.
  # docker-compose run kapacitor-cli
  kapacitor-cli:
    image: kapacitor:1.3.3
    entrypoint: bash
    environment:
      KAPACITOR_URL: http://kapacitor:9092
    links:
      - kapacitor
      - sms-notifier
    networks:
      - isengard-overlay
    volumes:
      - ./tickscripts:/usr/local/tickscripts
      - ./data/alerts:/var/log/alerts

  grafana:
    image: grafana/grafana:6.6.2
    # TODO consider using strip prefix instead of root url
    environment:
        GF_AUTH_ANONYMOUS_ENABLED: "true"
        GF_SERVER_DOMAIN: "isengard.local"
        GF_SERVER_ROOT_URL: "%(protocol)s://%(domain)s/grafana/"
        GF_SERVER_SERVE_FROM_SUB_PATH: "true"
    labels:
      - "traefik.http.routers.grafana.rule=PathPrefix(`/grafana`)"
    links:
      - influxdb
    networks:
      - isengard-overlay
    volumes:
      - grafana_arm_data:/var/lib/grafana


  # flask microservice for sending sms text
  # POST to http://sms-notifier:5000/send-sms
  sms-notifier:
    build: ./threshold_alerts/web
    environment:
      - TWILIO_ACCOUNT_SID
      - TWILIO_AUTH_TOKEN
      - TWILIO_SENDER
      - TWILIO_NOTIFY_TO
    labels:
      - "traefik.http.routers.sms-notifier.rule=PathPrefix(`/send-sms`)"
    networks:
      - isengard-overlay
    volumes:
      - ./threshold_alerts:/usr/local/threshold_alerts
      - ./notifier:/usr/local/notifier

volumes:
  grafana_arm_data:

networks:
  isengard-overlay:
    # Note: external networks are expected to exist prior to bringing this configuration up.
    external: True
