version: '3.0'
services:

    influxdb:
        image: influxdb:1.4.2
        ports:
            # http
            - "8086:8086"
            # admin interface port
            - "8083:8083"
        volumes:
            - ./data/influxdb:/var/lib/influxdb

    chronograf:          
        image: chronograf:1.4
        ports:
            - "8888:8888"
        volumes:
            - ./data/chronograf:/var/lib/chronograf
        links:
            - influxdb

    grafana:
        image: grafana/grafana
        ports:
            - "3000:3000"
        links:
            - influxdb
