version: '3.7'
services:
  dht:
    build: .
    restart: always
    privileged: true
    command: python3 -u write_dht_sensor_values.py -e $ENV_TAG -s 2302 -p 2

  sht:
    build: .
    restart: always
    privileged: true
    command: python3 -u write_sht_sensor_values.py -e $ENV_TAG -d 14 -c 4
