version: '3.7'
services:
  dht:
    build: .
    restart: always
    devices:
      - "/dev/gpiomem"
    networks:
      - isengard

  sht:
    build: .
    #restart: always
    devices:
      - "/dev/gpiomem"
    networks:
      - isengard

networks:
  isengard:
    external: True
