version: '3.7'

services:
  bedtime:
    build: .
    restart: always
    volumes:
      - "~/.python_hue:/root/.python_hue"
    networks:
      - isengard

networks:
  isengard:
    # Note: external networks are expected to exist prior to bringing this configuration up.
    external: True
