version: '3.7'

services:
  bedtime:
    build: .
    restart: always
    volumes:
      - "~/.python_hue:/root/.python_hue"
    labels:
      - "traefik.http.routers.bedtime.rule=Host(`isengard.local`) && PathPrefix(`/bedtime`)"
    networks:
      - isengard-overlay

networks:
  isengard-overlay:
    # Note: external networks are expected to exist prior to bringing this configuration up.
    external: True
